bambu_api/urls.py
from django.conf.urls import patterns, include, url
from bambu_api import autodiscover, site

autodiscover()
urlpatterns = patterns('',
	url(r'^', include(site.urls))
)

bambu_api/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.http import urlencode
from bambu_api.managers import *
from bambu_api import helpers
from datetime import datetime, timedelta
from time import time

REQUEST_LOGGER = helpers.get_request_logger()

class App(models.Model):
	admin = models.ForeignKey(User, related_name = 'owned_apps')
	name = models.CharField(max_length = 50)
	description = models.TextField()
	key = models.CharField(max_length = 18, editable = False)
	secret = models.CharField(max_length = 32, editable = False)
	status = models.PositiveIntegerField(default = 1, editable = False,
		choices = (
			(1, u'accepted'),
		)
	)
	
	callback_url = models.URLField(u'callback URL', max_length = 255, null = True, blank = True)
	deployment = models.CharField(
		max_length = 1, default = '',
		choices = (
			('w', u'Web'),
			('m', u'Mobile'),
			('d', u'Desktop')
		)
	)
	
	http_login = models.BooleanField(u'allow login via HTTP', default = False)
	http_signup = models.BooleanField(u'allow signup via HTTP', default = False)
	
	def __unicode__(self):
		return self.name
		
	def clean(self):
		if self.deployment == 'w' and not self.callback_url:
			raise ValidationError('A callback URL is required for web applications.')
	
	def save(self, *args, **kwargs):
		if not self.key and not self.secret:
			key = helpers.generate_random_key(18)
			secret = helpers.generate_random_key(32)
			
			while App.objects.filter(key__exact = key, secret__exact = secret).exists():
				secret = helpers.generate_random_key(32)
			
			self.key = key
			self.secret = secret
		
		super(App, self).save(*args, **kwargs)
	
	def log_request(self):
		if REQUEST_LOGGER.validate_request(self):
			REQUEST_LOGGER.log_request(self)
			return True
		else:
			return False
	
	@property
	def users(self):
		return User.objects.filter(
			pk__in = self.tokens.filter(user__isnull = False, token_type = 2).values_list('user',
				flat = True
			)
		)
	
	class Meta:
		ordering = ('name',)
		db_table = 'api_app'

class Nonce(models.Model):
	token_key = models.CharField(max_length = 18)
	consumer_key = models.CharField(max_length = 32)
	key = models.CharField(max_length = 255)
	
	def __unicode__(self):
		return u'Nonce %s for %s' % (self.key, self.consumer_key)
	
	class Meta:
	    db_table = 'api_nonce'

class Token(models.Model):
	key = models.CharField(max_length = 18)
	secret = models.CharField(max_length=32)
	verifier = models.CharField(max_length = 10)
	token_type = models.PositiveIntegerField(choices = 
		(
			(1, u'Request'),
			(2, u'Access')
		)
	)
	
	timestamp = models.PositiveIntegerField(default = long(time()))
	approved = models.BooleanField(default = False)
	
	user = models.ForeignKey(User, null = True, blank = True, related_name = 'tokens')
	app = models.ForeignKey(App, related_name = 'tokens')
	callback = models.CharField(max_length = 255, null=True, blank = True)
	callback_confirmed = models.BooleanField(default = False)
	
	objects = TokenManager()
	
	def __unicode__(self):
		return u'%s Token %s for %s' % (
			self.get_token_type_display(), self.key, self.app
		)
	
	def to_string(self, only_key = False):
		token_dict = {
			'oauth_token': self.key, 
			'oauth_token_secret': self.secret,
			'oauth_callback_confirmed': 'true',
		}
		
		if self.verifier:
			token_dict['oauth_verifier'] = self.verifier
		
		if only_key:
			del token_dict['oauth_token_secret']
		
		return urlencode(token_dict)
	
	def save(self, *args, **kwargs):
		if not self.key and not self.secret:
			key = helpers.generate_random_key(18)
			secret = helpers.generate_random_key(32)
			
			while Token.objects.filter(
				key__exact = key, secret__exact = secret
			).exists():
				secret = helpers.generate_random_key(32)
			
			self.key = key
			self.secret = secret
		
		super(Token, self).save(*args, **kwargs)
	
	def get_callback_url(self):
		if self.callback and self.verifier:
			parts = urlparse.urlparse(self.callback)
			scheme, netloc, path, params, query, fragment = parts[:6]
			
			if query:
				query = '%s&oauth_verifier=%s' % (query, self.verifier)
			else:
				query = 'oauth_verifier=%s' % self.verifier
			
			return urlparse.urlunparse((scheme, netloc, path, params,
				query, fragment))
		
		return self.callback
	
	def set_callback(self, callback):
		if callback != 'oob':
			self.callback = callback
			self.callback_confirmed = True
			self.save()
	
	class Meta:
	    db_table = 'api_token'

class RequestBatch(models.Model):
	app = models.ForeignKey(App, related_name = 'requests')
	timestamp = models.PositiveIntegerField(default = 0)
	count = models.PositiveIntegerField(default = 1)
	
	class Meta:
		unique_together = ('app', 'timestamp')
		db_table = 'api_requestbatch'

bambu_api/forms.py
"""
Forms used by the built-in user API endpoints to register users
"""

from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
	def save(self, commit = True):
		user = User.objects.create_user(
			username = self.cleaned_data['username'],
			password = self.cleaned_data['password'],
			email = self.cleaned_data.get('email')
		)
		
		user.first_name = self.cleaned_data.get('first_name', '')
		user.last_name = self.cleaned_data.get('last_name', '')
		user.save()
		
		return user
	
	class Meta:
		model = User
		fields = ('username', 'password', 'first_name', 'last_name', 'email')

bambu_api/templates/api/401.html
{% extends 'base.html' %}
{% load url from future %}

{% block content %}
	<div class="page-header">
		<h1>Access denied</h1>
	</div>
	
	<p>
		Sorry, but the details you&rsquo;ve provided are incorrect. Please try again<br />
		You can read the <a href="{% url 'api:doc' %}">API documentation</a> if you need help.
	</p>
{% endblock content %}

bambu_api/templates/api/apps/delete.html
{% extends 'api/base.html' %}

{% block form_content %}
	<h2>{{ app.name }} <small>Delete</small></h2>
	<hr />
		
	<p>Are you sure you want to delete this app?</p>
	
	<div class="alert alert-block alert-warning">
		<h4 class="alert-heading">Warning!</h4>
		<p>Once deleted, no-one previously using this app will be able to login with it again.</p>
	</div>
	
	<a class="btn btn-danger" href="?confirm=1">Yes, delete it</a>
	<a class="btn btn-default" data-dismiss="modal">No, don&rsquo;t delete it</a>
{% endblock form_content %}

bambu_api/templates/api/apps/edit.html
{% extends 'api/base.html' %}
{% load humanize icons %}
{% load url from future %}

{% block form_content %}
	<h2>{{ app.name }} <small>View and edit</small></h2>
	<hr />
	
	<form action="{% url 'api:edit_app' app.pk %}" method="post" class="form-horizontal">
		{% include 'form.inc.html' %}
		
		<div class="control-group">
			<span class="control-label">API key</span>
			<div class="controls">
				<input type="text" value="{{ app.key }}" readonly />
			</div>
		</div>
		
		<div class="control-group">
			<span class="control-label">API secret</span>
			<div class="controls">
				<input type="text" value="{{ app.secret }}" readonly />
			</div>
		</div>
		
		<div class="form-actions">
			{% csrf_token %}
			<button type="submit" class="btn btn-success">{% icon 'ok' 'white' %} Save app</button>
			<a class="btn btn-danger" data-toggle="modal" data-target="#delete-confirm" href="{% url 'api:delete_app' app.pk %}">{% icon 'remove' 'white' %} Delete</a>
		</div>
	</form>
	
	{% with app.users.count as user_count %}
		{% if user_count > 0 %}
			<p>Your app has <strong>{{ user_count|apnumber }} user{{ user_count|pluralize }}</strong>.</p>
		{% endif %}
	{% endwith %}
	
	<div class="modal hide fade" id="delete-confirm">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">&times;</a>
			<h3>Delete app</h3>
		</div>
		
		<div class="modal-body">
			<p>Are you sure you want to delete this app?</p>
			
			<div class="alert alert-block alert-warning">
				<h4 class="alert-heading">Warning!</h4>
				<p>Once deleted, no-one previously using this app will be able to login with it again.</p>
			</div>
		</div>
		
		<div class="modal-footer">
			<a href="#" class="btn btn-primary" data-dismiss="modal">No</a>
			<a href="{% url 'api:delete_app' app.pk %}?confirm=1" class="btn secondary">Yes</a>
		</div>
	</div>
{% endblock form_content %}

bambu_api/templates/api/apps/list.html
{% extends 'api/base.html' %}
{% load icons %}
{% load url from future %}

{% block form_content %}
	{% if apps.count > 0 %}
		<h2>Your apps</h2>
		<hr />
		
		<table class="table table-striped">
			<thead>
				<tr>
					<th>App name</th>
					<th>Key</th>
					<th>Deployment</th>
					<th width="15%">Actions</th>
				</tr>
			</thead>
			
			<tbody>
			{% for app in apps %}
				<tr>
					<td><a href="{% url 'api:edit_app' app.pk %}">{{ app.name }}</a></td>
					<td>{{ app.key }}</td>
					<td>{{ app.get_deployment_display }}</td>
					<td>
						<a class="btn btn-danger" data-toggle="modal" data-target="#delete-confirm" href="{% url 'api:delete_app' app.pk %}">{% icon 'remove' 'white' %} Delete</a>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		
		<hr />
	{% endif %}
	
	{% if app_form %}
		<h2>Create a new app</h2>
		
		<form action="{% url 'api:add_app' %}" method="post" class="form-horizontal">
			{% include 'form.inc.html' with form=app_form %}
			
			<div class="form-actions">
				{% csrf_token %}
				<button type="submit" class="btn btn-success">{% icon 'ok' 'white' %} Save new app</button>
			</div>
		</form>
	{% endif %}
	
	<div class="modal hide fade" id="delete-confirm">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">&times;</a>
			<h3>Delete app</h3>
		</div>
		
		<div class="modal-body">
			<p>Are you sure you want to delete this app?</p>
			
			<div class="alert alert-block alert-warning">
				<h4 class="alert-heading">Warning!</h4>
				<p>Once deleted, no-one previously using this app will be able to login with it again.</p>
			</div>
		</div>
		
		<div class="modal-footer">
			<a href="#" class="btn btn-primary" data-dismiss="modal">No</a>
			<a class="btn secondary">Yes</a>
		</div>
	</div>
{% endblock form_content %}

{% block javascript %}
	{{ block.super }}
	
	<script>
		$('a[data-target="#delete-confirm"]').bind('click',
			function(e) {
				$('#delete-confirm .btn.secondary').attr('href',
					$(this).attr('href') + '?confirm=1'
				);
			}
		);
	</script>
{% endblock javascript %}

bambu_api/templates/api/base.html
{% extends 'base.html' %}
{% load url from future %}

{% block page_header %}
	<h1>Developer resources</h1>
{% endblock page_header %}

{% block sidebar %}
	<h2>Endpoints</h2>
	
	<ul class="unstyled">
		{% for resource in resources %}
			<li>
				<h3><a href="{{ resource.url }}">{{ resource.name }}</a></h3>
				{% if resource.children %}
					<ul class="unstyled">
						{% for child in resource.children %}
							<li><a href="{{ child.url }}">{{ child.name|title }}</a></li>
						{% endfor %}
					</ul>
				{% endif %}
			</li>
		{% endfor %}
	</ul>
	
	{% if apps_supported and request.user.is_authenticated %}
		<h3>Your apps</h3>
		<p><a href="{% url 'api:apps' %}">Manage your apps</a></p>
	{% endif %}
{% endblock sidebar %}

bambu_api/templates/api/doc/app_index.html
{% extends 'api/doc/base.html' %}
{% load markup %}

{% block form_content %}
	<h2>{{ name }}</h2>
	
	{% for api in apis %}
		<h3><a href="{{ api.url }}">{{ api.title }}</a></h3>
		{{ api.doc|restructuredtext }}
	{% endfor %}
{% endblock form_content %}

bambu_api/templates/api/doc/base.html
{% extends 'api/base.html' %}

bambu_api/templates/api/doc/endpoints.inc.html
<table class="table">
	<tr>
		<th width="20%">List {{ verbose_name_plural }}</th>
		<td>
			<code>http://{{ SITE.domain }}{{ urls.list.url|safe }}</code><br />
			Allowed methods: {% for method in urls.list.allowed_methods %}{% if forloop.last %}and {% endif %}<code>{{ method }}</code>{% if not forloop.last %}, {% endif %}{% endfor %}
		</td>
	</tr>
	
	<tr>
		<th width="20%">Single {{ verbose_name }}</th>
		<td>
			<code>http://{{ SITE.domain }}{{ urls.object.url|safe }}</code><br />
			Allowed methods: {% for method in urls.object.allowed_methods %}{% if forloop.last %}and {% endif %}<code>{{ method }}</code>{% if not forloop.last %}, {% endif %}{% endfor %}
		</td>
	</tr>
</table>

<p>Supported formats: {% for format in formats %}{% if forloop.last %}and {% endif %}<abbr class="initialism">{{ format }}</abbr>{% if not forloop.last %}, {% endif %}{% endfor %}

bambu_api/templates/api/doc/index.html
{% extends 'api/doc/base.html' %}
{% load markup %}

{% block form_content %}
	<h2>Welcome to the {{ SITE.name }} API</h2>
	
	<p>
		{{ SITE.name }} uses a RESTful API. If you&rsquo;re not familiar with it,
		you can read the <a href="http://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank">Wikipedia entry</a>
		on the topic. In short however, you can perform four types of action via the {{ SITE.name }}
		REST API:
	</p>
	
	<dl class="dl-horizontal">
		<dt>GET</dt>
		<dd>Return a single record or a list of records</dd>
		
		<dt>POST</dt>
		<dd>Create a new record</dd>
		
		<dt>PUT</dt>
		<dd>Update an existing record</dd>
		
		<dt>DELETE</dt>
		<dd>Remove a record</dd>
	</dl>
	
	<p>
		There are a number of API endpoints divided up into sections. Please use the
		<strong>Endpoints</strong> menu to find your way around.
	</p>
	
	{% if auth %}
		<h3>{{ auth.name }}</h3>
		{{ auth.doc|restructuredtext }}
	{% endif %}
{% endblock form_content %}

bambu_api/templates/api/doc/model.html
{% extends 'api/doc/base.html' %}
{% load markup prettycode staticfiles %}

{% block form_content %}
	<h2>{{ name }}</h2>
	
	{{ doc|restructuredtext }}
	{% include 'api/doc/endpoints.inc.html' %}
	
	<hr />
	
	<h3>Examples</h3>
	
	<ul class="nav nav-tabs">
		<li class="active">
			<a href="#example-list" data-toggle="tab">{{ verbose_name|capfirst }} list</a>
		</li>
		
		<li>
			<a href="#example-object" data-toggle="tab">Single {{ verbose_name }}</a>
		</li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane active" id="example-list">
			<h4>Request</h4>
			<pre>GET {{ urls.list.example.url }}
Host: {{ SITE.domain }}</pre>
			
			<h4>Response</h4>
			<pre class="api-example prettyprint">{{ urls.list.example.response|prettyjson }}</pre>
		</div>
		
		<div class="tab-pane" id="example-object">
			<h4>Request</h4>
			<pre>GET {{ urls.object.example.url }}
Host: {{ SITE.domain }}</pre>
			
			<h4>Response</h4>
			<pre class="api-example prettyprint">{{ urls.object.example.response|prettyjson }}</pre>
		</div>
	</div>
	
	{% if inlines %}
		{% for inline in inlines %}
			<h3>
				<a href="{{ inline.url }}">{{ inline.name }}</a>
			</h3>
			
			{{ inline.doc.splitlines.0|restructuredtext }}
		{% endfor %}
	{% endif %}
{% endblock form_content %}